spring.application.name=pl-core-data

# Connection Settings
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/premier_league_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.connection.autocommit=true

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable JSONB support (for that deep player stats data)
spring.jpa.properties.hibernate.jdbc.type_null_checked=true
